general:
  artifacts:
    - "~/outputs"
machine:
  services:
    - docker

dependencies:
  cache_directories:
    - "~/docker"
    - "~/data"

  override:
  # OSF drive link to test data, thanks to Gael V. and Chris G.
  # "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549c2b83f6901d357d15f"
    - if [[ ! -d ~/data/ds005-deriv-light/derivatives ]]; then wget -c -O ${HOME}/ds005-deriv-light.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549c2b83f6901d357d15f" && mkdir -p ${HOME}/data && tar -xf ${HOME}/ds005-deriv-light.tar -C ${HOME}/data; fi
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    - git describe --tags > version
    - docker build -t bids/hyperalignment . :
        timeout: 21600
    - mkdir -p ~/docker; docker save "bids/hyperalignment" > ~/docker/image.tar
    - mkdir -p ${HOME}/outputs

test:
  override:
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light/derivatives:/bids_dataset -v ${HOME}/outputs:/outputs bids/hyperalignment /bids_dataset /outputs participant --participant_label 01 --task mixedgamblestask --run 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light/derivatives:/bids_dataset -v ${HOME}/outputs:/outputs bids/hyperalignment /bids_dataset /outputs participant --participant_label 02 --task mixedgamblestask --run 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light/derivatives:/bids_dataset -v ${HOME}/outputs:/outputs bids/hyperalignment /bids_dataset /outputs participant --participant_label 03 --task mixedgamblestask --run 01 :
        timeout: 21600
    - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds005-deriv-light/derivatives:/bids_dataset -v ${HOME}/outputs:/outputs bids/hyperalignment /bids_dataset /outputs group :
        timeout: 21600

deployment:
  hub:
    owner: BIDS-Apps
    tag: /.*/
    commands:
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME}:latest; fi :
          timeout: 21600
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG; fi :
          timeout: 21600
